import Vue from 'vue'
import { Checkbox,Input,FormItem,Form,Pagination,Row,TableColumn,Table,MenuItem,MenuItemGroup,Submenu,Menu,Col,Main,Aside,Header,Container,Button } from 'element-ui'

Vue.use(Button)
Vue.use(Container)
Vue.use(Header)
Vue.use(Aside)
Vue.use(Main)
Vue.use(Col)
Vue.use(Menu)
Vue.use(Submenu)
Vue.use(MenuItemGroup)
Vue.use(MenuItem)
Vue.use(Table)
Vue.use(TableColumn)
Vue.use(Row)
Vue.use(Pagination)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Input)
Vue.use(Checkbox)
